name: build

on:
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v4
      with:
        python-version: '3.13'

    - name: Install dependencies
      run: pip3 install -r requirements.txt
      
    - name: Build docs
      run: |
        mkdocs -v build
