name: Sync Linux Software List

on:
  schedule:
    - cron: '0 0 * * 0'  # 每周日 UTC 0 点（北京时间早上 8 点）
  workflow_dispatch:      # 支持手动触发

permissions:
  contents: write         # 允许推送更改

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4
        with:
          submodules: false

      - name: Clone linuxsoftwarelist repo
        run: |
          rm -rf appendix/linuxsoftwarelist
          mkdir -p appendix
          git clone --depth=1 https://github.com/hust-open-atom-club/linuxsoftwarelist appendix/linuxsoftwarelist || {
            echo "[Error] Failed to clone linuxsoftwarelist repository."
            exit 1
          }
          # 删除子目录的 .git 文件夹，以避免被当作 submodule
          rm -rf appendix/linuxsoftwarelist/.git
          
          # 这行可以保留，用于清理可能存在的旧的 submodule 缓存
          git rm -r --cached appendix/linuxsoftwarelist 2>/dev/null || true
          
      - name: Commit and push updates
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git config --global --add safe.directory "$PWD"

          git add appendix/linuxsoftwarelist

          if git diff --staged --quiet; then
            echo "[Info] No changes detected — nothing to commit."
            exit 0
          fi

          git commit -m "Auto-sync linuxsoftwarelist $(date -u +'%Y-%m-%d %H:%M:%S')" || {
            echo "[Warning] No changes to commit."
            exit 0
          }
          git push || {
            echo "[Error] Failed to push changes."
            exit 1
          }
          echo "[Success] linuxsoftwarelist updated and pushed successfully."
